version: '3.2'

services:
  papercups-web:
    image: papercups/papercups-dev:latest
    ports:
      - '3000:3000'
      - '4000:4000'
    command:
      - ./entrypoint.sh
    depends_on:
      - db-1
    environment:
      DATABASE_URL: 'ecto://postgres:postgres@db-1/postgres'
  db-1:
    image: postgres:alpine
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
